### PR TITLE
moved templates into netweaver/templates

### PR DESCRIPTION
**Pull request by cschneemann**
Moved template files from templates dir as subdirectory
below netweaver to be compatible witch gitfs.

### CODE REVIEW

**Comment by cschneemann** [comment]
@yeoldegrove can I ask you for a review?
Reopened the PR after you have changed the main branch.

**Review by arbulu89 — APPROVED** [review]
LGTM.

In other formulas, this files are included as in this new change, so it looks a common practice. In other formulas, the folder is named `files`So my unique suggestion could be to have them in `files/templates`. But well the current solution works as well.

Other formulas as reference:
https://github.com/salt-formulas

https://github.com/salt-formulas/salt-formula-prometheus
https://github.com/salt-formulas/salt-formula-rsyslog

**Comment by yeoldegrove** [comment]
@cschneemann Do you mind implementing this for these formulas as well?

https://github.com/SUSE/drbd-formula
https://github.com/SUSE/habootstrap-formula
https://github.com/SUSE/saphanabootstrap-formula

**Comment by cschneemann** [comment]
@arbulu89 

I did not want to change too much in the sls-files itself, just removed the copytask from the spec file and moved the files already in the repo.

Shall I put everything below a files directory here already?

**Comment by cschneemann** [comment]
@yeoldegrove 
> @cschneemann Do you mind implementing this for these formulas as well?
> 
> https://github.com/SUSE/drbd-formula https://github.com/SUSE/habootstrap-formula https://github.com/SUSE/saphanabootstrap-formula

can do that in the next days

**Comment by yeoldegrove** [comment]
> Shall I put everything below a files directory here already?

Let's just keep it as it is for now (like you commited).
My main reason for this is that there might be dependencies in other code out there.
e.g. for the `habootstrap-formula` there is code like this:
https://github.com/SUSE/ha-sap-terraform-deployments/blob/d5a5856cf2265b63379bc9f91d0d84845261917c/pillar_examples/automatic/netweaver/cluster.sls#L66

**Comment by yeoldegrove** [comment]
@cschneemann Could you also bump `_service` and `*.changes` so that we can directly release this?

**Review by yeoldegrove — APPROVED** [review]
LGTM - Looking forward to your next PRs ;)

**Pull request merged**
