### PR TITLE
Move the step of update sapservices

### PR DESCRIPTION
**Pull request by smpsgill**
update sapservices state after stoping the instances

### CODE REVIEW

**Review by arbulu89 — COMMENTED** [review]
@Simranpal I don't really know if we can do this. The `sapservices_updated` state uses the sapcontrol command, and if the instance is stopped, the command don't usually work... Maybe it works this time due the timings, but I would like to be sure of this. Just try to stop the service manually and run the `GetSystemInstanceList` command to see if it always work.

Besides that, I'm not sure why this change would affect to the next start process. The unique explanation I can find is that the Stop was failling, and this change fixes that avoid issues in the Start. 

I would like to find at least a explanation why this change fixes the issue to see that is not something random.

**Comment by smpsgill** [comment]
Hi @arbulu89 I suspected that shutdown was not complete, maybe the stop state was not graceful and failed the next Start process. But this is speculation and not concrete. Also as per the guide steps, it had stop stage before updating `'/usr/sap/sapservices'`

And you are correct. I tried with more deployments and it infact seems random. I faced the issue now with one deployment. And I can also confirm that the `GetSystemInstanceList` did not run after I stopped the service manually.

`'/usr/sap/sapservices'` is being used by `sapstartsrv` in general to start/stop instances, by installer,users(via `sapcontrol`) as well as cluster in our case. Now I can only think of maybe adding a wait time before issuing the stop command.
All of the steps we are doing are correct, as per the guide, and it might be an issue with the swpm version maybe.

**Comment by arbulu89** [comment]
@Simranpal After merging https://github.com/SUSE/sapnwbootstrap-formula/pull/26 I think we can close this PR. What do you think?

**Comment by smpsgill** [comment]
> @Simranpal After merging #26 I think we can close this PR. What do you think?

Yes @arbulu89 lets close this

**Pull request closed without merging**
